### ISSUE TITLE
Scrape department names

### ISSUE THREAD

**Issue by alyssia-chen** [Alyssia-Chen/Toothless#13]
Examples: ICS, ACC, ITM, BUS, ACM

Scrape from star? class availabilities page?

Check out index page of class availabilities website

**Comment by mujtaba-a-quadri** [comment]
https://docs.google.com/document/d/11ZIS-ntNo5t6RrzToFVi5VpxCaoPrmFUYZrO2k1s9JU/edit

human scrape 😉
