### ISSUE TITLE
What is the intent of the "Add" button on the CRN page?

### ISSUE THREAD

**Issue by zhaol** [Alyssia-Chen/Toothless#17]
This comment might be premature as you are still working on the application.
I just wanted to track the thought here just in case it's supposed to be doing something.

Page link: https://stellation.herokuapp.com/search/?CRN__icontains=&course__icontains=&title__icontains=income
Screenshot of button: 
<img width="983" alt="CRN_Add_Button" src="https://user-images.githubusercontent.com/5201803/123508158-6572bc80-d609-11eb-9e83-9fbd22577bfb.png">

**Comment by zhaol** [comment]
Oh I think I see it now.  Is it suppose to add the course to my user page under "choices"?

**Comment by alyssia-chen** [comment]
Yep yep! It will hopefully be clearer that that's supposed to happen!

**Comment by zhaol** [comment]
Sorry, but is it possible to keep this issue ticket open so that I can track it until the user interface alerts the user that the course was added to the choices?

**Comment by alyssia-chen** [comment]
Oh yes sure, no problem!

**Comment by zhaol** [comment]
the new alert fixes this issue
