### ISSUE TITLE
[optional] All Users are able to view the everyone's notes

### ISSUE THREAD

**Issue by zhaol** [Alyssia-Chen/Toothless#2]
I'm not sure if the project will eventually remove notes and if it's a feature for everyone to collectively view a global list of notes.

Just a thought that it is possible to have notes belong to a user and only that user can view/modify his/her own note.

**Comment by alyssia-chen** [comment]
Our plan is to make the notes belong to the user and will hopefully get that sorted out over the weekend, but if we can't, we'll definitely ask you for help about that on Monday!
